import type { ChatMessage } from './types'

// Client-side conversation export. Reads only what is already in memory and
// writes to a one-shot Blob download — nothing is persisted in the browser.

export function conversationToMarkdown(title: string, messages: ChatMessage[]): string {
  const lines: string[] = [`# ${title}`, '', `_Exported ${new Date().toISOString()}_`, '']
  for (const message of messages) {
    if (message.id === 'welcome') continue
    const who = message.role === 'nova' ? 'NOVA' : 'You'
    const stamp = message.created_at ? new Date(message.created_at).toISOString() : ''
    lines.push(`## ${who}${stamp ? ` · ${stamp}` : ''}`, '')
    if (message.media?.kind === 'image_input') lines.push('![Attached image](attachment)', '')
    if (message.media?.kind === 'image_output') lines.push('![Generated by NOVA](generated)', '')
    if (message.media?.kind === 'audio_output') lines.push('[Spoken reply](audio)', '')
    lines.push(message.text, '')
  }
  return lines.join('\n')
}

export function downloadMarkdown(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}
